import '@/styles/globals.css';
import { AntdRegistry } from '@ant-design/nextjs-registry';
import { ConfigProvider } from 'antd';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import NextTopLoader from 'nextjs-toploader';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body className={inter.className}>
        <ConfigProvider theme={{ cssVar: true }}>
          <AntdRegistry>
            <NextTopLoader color='#1677ff' showSpinner={false} />
            {children}
          </AntdRegistry>
        </ConfigProvider>
      </body>
    </html>
  );
}
